import React from 'react';
import { motion } from 'motion/react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { BookOpen, AlertTriangle, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { NotesData } from '@/types';
import { fadeIn } from '@/lib/animations';

interface NotesTabProps {
  data: NotesData;
}

export const NotesTab = ({ data }: NotesTabProps) => {
  return (
    <motion.div
      variants={fadeIn}
      initial="initial"
      animate="animate"
      className="space-y-6 h-full flex flex-col"
    >
      {data.isAiGenerated && (
        <Alert variant="destructive" className="bg-amber-500/10 border-amber-500/20 text-amber-600 dark:text-amber-400">
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>AI Generated Content</AlertTitle>
          <AlertDescription>
            {data.warning || "No specific notes were found for this topic. These notes were generated by AI based on general knowledge and PYQ context."}
          </AlertDescription>
        </Alert>
      )}

      <Card className="flex-1 border-glass-border bg-glass backdrop-blur-xl shadow-sm shadow-glass-shadow overflow-hidden flex flex-col">
        <CardHeader className="pb-4 border-b border-glass-border bg-primary/5 shrink-0">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <BookOpen className="h-5 w-5 text-primary" />
              <CardTitle>Study Notes</CardTitle>
            </div>
            <div className="flex gap-2">
              {data.sources.map((source, idx) => (
                <Badge key={idx} variant="outline" className="text-xs bg-background/50">
                  {source}
                </Badge>
              ))}
              {data.isAiGenerated && (
                <Badge variant="secondary" className="text-xs gap-1 bg-amber-500/10 text-amber-600 border-amber-500/20">
                  <Sparkles className="h-3 w-3" /> AI Generated
                </Badge>
              )}
            </div>
          </div>
          <CardDescription>
            Comprehensive summary and key points for revision
          </CardDescription>
        </CardHeader>
        <CardContent className="p-6 overflow-y-auto custom-scrollbar flex-1">
          <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none prose-headings:text-foreground prose-p:text-muted-foreground prose-strong:text-foreground prose-li:text-muted-foreground">
            <ReactMarkdown>{data.content}</ReactMarkdown>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
};
